version: '3.8'

networks: 
    laravel:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "8090:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel
    
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=lugasdev
            - MYSQL_USER=lugasdev
            - MYSQL_PASSWORD=lugasdev
            - MYSQL_ROOT_PASSWORD=secret
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        networks: 
            - laravel
    
    php:
        build:
            args: 
                user: lugasdev
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravel
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        ports: 
            - "8082:80"
        environment: 
            - MYSQL_USERNAME=lugasdev
            - MYSQL_ROOT_PASSWORD=lugasdev
            - PMA_HOST=mysql
        depends_on: 
            - mysql
        networks: 
            - laravel
        
    